/*
 * sbIPlaydarService XPCOM Interface
 *
 * Copyright (c) 2009 Steven M. Lloyd
 * steve@repeatingbeats.com
 *
 *
 * This file is part of the Birdplaydar Songbird add-on.
 *
 * This file may be licensed under the terms of of the
 * GNU General Public License Version 2 (the ``GPL'').
 *
 * Software distributed under the License is distributed
 * on an ``AS IS'' basis, WITHOUT WARRANTY OF ANY KIND, either
 * express or implied. See the GPL for the specific language
 * governing rights and limitations.
 *
 * You should have received a copy of the GPL along with this
 * program. If not, go to http://www.gnu.org/licenses/gpl.html
 * or write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

#include "nsISupports.idl"

interface sbIMediaList;
interface sbIPropertyArray;
interface sbIMediaListListener;
interface sbIPlaydarServiceListener;
interface sbILibrary;
interface sbIServicePaneNode;

[scriptable, uuid(57b773d6-7a0f-41f1-8ef1-768109d47e1c)]
interface sbIPlaydarService : nsISupports
{

  attribute AString versionString;
  attribute sbILibrary playdarLibrary;
  attribute sbIServicePaneNode playdarServiceNode;
  attribute AString sourcePropID;
  attribute AString scorePropID;

  AString registerClient(in sbIPlaydarServiceListener listener,
                         in boolean keepTracksHidden);

  void unregisterClient(in AString cid,
                        in boolean removeClientList,
                        in boolean removeAllTracks,
                        [optional] in boolean removeHiddenTracks);

  void addClientListListener(in AString cid,
                             in sbIMediaListListener listener,
                             [optional] in boolean ownsWeak,
                             [optional] in unsigned long flags,
                             [optional] in sbIPropertyArray filter);

  sbIMediaList getClientList(in AString cid);

  void stat();

  void resolve(in AString cid,
               in AString artist,
               in AString album,
               in AString track,
               [optional] in AString qid,
               [optional] in AString url);

  void showClientListInServicePane (in AString cid,
                                    in AString name); 
  
  
};
